# Node.js with Angular

# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

i'm adding nonsense to make sure my changes do not affect the original

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - NotFightClub/Angular
pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'
  

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
  workingDirectory: 'NotFightClub/Angular'



- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: 'NotFightClub/Angular/dist/Angular'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '8f7a3d65-6e62-4cf4-b5a9-193406d2e5c2'
    appType: 'webApp'
    WebAppName: 'NotFightClub'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
